### ISSUE TITLE
Include XZC

### ISSUE THREAD

**Issue by treygriffith** [treygriffith/swap-compatibility#3]
A [pull request on the atomicswap repo](https://github.com/decred/atomicswap/pull/50) implements XZC as an atomic-swap-compatible currency, so it should be included on the chart.

**Comment by devwarrior777** [comment]
I checked https://swapready.net/ and did not find Zcoin (XZC)

Support for Zcoin was recently merged in to Decred atomic swaps in https://github.com/decred/atomicswap/pull/64

Actually you guys had been tracking in another earlier PR: https://github.com/decred/atomicswap/pull/50 which I closed out due to the need to reopen a less messy PR ;-)

Hope we can close the circle now and be included in your listing

Cheers

**Comment by treygriffith** [comment]
@devwarrior777 thanks for your interest. Can you provide:

- Supported hash functions (Bitcoin derivatives typically include RIPEMD160, SHA1, and SHA256) and a link to the code that supports them
- Transaction malleability fix status (e.g. is SegWit on mainnet) and supporting evidence
- Support for Hashed Time Locked Contracts (typically by supporting OP_CHECKLOCKTIMEVERIFY, introduced in BIP65) and a link to supporting code

Thanks for the link to the swap implementation, that helps!

**Comment by devwarrior777** [comment]
## Zcoin (XZC) is a port of bitcoin 0.13.2 with added Zerocoin privacy.

**Hash functions and HTLC Support::**
>https://github.com/zcoinofficial/zcoin/blob/defe6065486d1c4b457eb7c5ef07f087ae0abfd2/src/script/script.h#L156

- RIPEMD160
- SHA1
- SHA256
- CHECKLOCKTIMEVERIFY

CHECKSEQUENCEVERIFY is implemented but  __Not enabled__ at this time.

**Tx Malleability, Segwit:**

Segwit code exists but is __Not enabled__ and the bitcoin Tx version is still v1.

- LN ready has some way to go I think . . .

Thanks for your help.
