### ISSUE TITLE
Explain the criteria

### ISSUE THREAD

**Issue by donpdonp** [treygriffith/swap-compatibility#7]
Hey thanks for this site! I'm excitedly learning and watching the atomic swap/lightening/distributed exchanges development and think this site is an interesting resource.

What would help a lot is a section on the page that shows the criteria from the hover-over window and explains what each criteria means. Most devs will know the hash functions, and bitcoin-friendly devs will know the Hashlock Timelock, but a public preimage is particular puzzling. As far as I can tell the preimage is simply the secret generated by Alice and Bob at the start of the atomic swap process. A public preimage I'm guessing means the secret gets exposed in the transaction once its submitted to the network, but I'm not sure if thats right. 

# OnChain Criteria

* supports HTLC
* supports public preimages
* Common hash functions (RIPEMD160, SHA1, SHA256) 
* Fixed transaction maleability (Payment Channel Criteria only)

Transaction malleability fix is very murky. Chains with segwit have malleability fixed for segwit transactions. Bitcoin Cash has its own malleability fix for all transactions but I'm finding conflicting info as to what the fix actually is and when it was applied.

**Comment by treygriffith** [comment]
You're probably right that an explanation page would make sense.

I'll do my best to explain here and use it in the meantime.

- **Supports HTLC**
Whether the currency supports [Hashed Timelock Contracts](https://en.bitcoin.it/wiki/Hashed_Timelock_Contracts), which allow for a trustless on-chain atomic swap setup, where the hash is used for the swap, and the timelock is used as a bailout if the swap doesn't go through (making the process atomic and trustless)

- **Supports public preimages**
Whether the transaction that includes the preimage used to redeem the HTLC is public, i.e. can be viewed by anyone. Without this, the transaction can't go across chains, since one party can redeem the HTLC without revealing the preimage to the other party. This reveal is the essential portion of the swap. As a criteria it's not as useful, since I don't know of any mainstream currencies or tokens for which this isn't supported (excepting Monero, which doesn't support scripts).

- **Common hash functions**
In order for a swap between two parties to work, the chains must support the same hash function. In order to set up the swap, parties share the hash ahead of time, and the preimage to redeem. If the same hash function isn't supported, you can't do that trustlessly.

- **Fixed transaction malleability**
This one is intentionally a bit murky. I'm not as familiar with all of the transaction malleability fix options that exist, but I know that one of the precursors to building a functional payment channel network like Lightning is that it gets fixed. Ultimately, the payment channel swaps will depend more heavily on interoperability between specific implementations rather than the criteria that I've used. For example, LND, the most popular Lightning implementation, only works with SegWit currencies.
In my experience, it is quite difficult to find information about not only what the fix is, but also when it was activated if it was a difficult softfork like SegWit.

I hope this helps. If there is anything that I left out or was not clear on, let me know.
